#!/bin/bash

BASE_URL="https://raw.githubusercontent.com/STMicroelectronics/cmsis_device_h7/master/Source/Templates/gcc"
LINKER_SCRIPT_URL="${BASE_URL}/linker"
STARTUP=startup_${MCU_FAMILY}.s
STARTUP_SCRIPT_URL="$BASE_URL/${STARTUP}"
CM7_LINKER=${MCU_FAMILY}_flash_CM7.ld
CM4_LINKER=${MCU_FAMILY}_flash_CM4.ld
SRAM1_LINKER=${MCU_FAMILY}_sram1_CM7.ld
SRAM2_LINKER=${MCU_FAMILY}_sram2_CM4.ld
CM7_LINKER_SCRIPT_URL="${BASE_URL}/linker/${CM7_LINKER}"
CM4_LINKER_SCRIPT_URL="${BASE_URL}/linker/${CM7_LINKER}"
SRAM1_LINKER_SCRIPT_URL="${BASE_URL}/linker/${SRAM1_LINKER}"
SRAM2_LINKER_SCRIPT_URL="${BASE_URL}/linker/${SRAM2_LINKER}"

curl -L -o ${STARTUP} "$STARTUP_SCRIPT_URL"
curl -L -o ${CM7_LINKER} "$CM7_LINKER_SCRIPT_URL"
curl -L -o ${CM4_LINKER} "$CM4_LINKER_SCRIPT_URL"
curl -L -o ${SRAM1_LINKER} "$SRAM1_LINKER_SCRIPT_URL"
curl -L -o ${SRAM2_LINKER} "$SRAM2_LINKER_SCRIPT_URL"

mv ${STARTUP} "${PROJECT_NAME}/Startup"
mv ${CM7_LINKER} "${PROJECT_NAME}/Startup"
mv ${CM4_LINKER} "${PROJECT_NAME}/Startup"
mv ${SRAM1_LINKER} "${PROJECT_NAME}/Startup"
mv ${SRAM2_LINKER} "${PROJECT_NAME}/Startup"


